### ISSUE TITLE
Problem while trying filter only

### ISSUE THREAD

**Issue by NekoKawaii** [pocketsnizort/pythOCR#2]
Python 3.6.2 32 bits, PythOCR 1.83, Win 10 x64

> `PS C:\Users\a\Documents\pythOCR> C:\Python36-32\python.exe .\pythoCR.py  -c .\config\userconfig_2.ini --vpy "My-vpy.vpy" --mode filter --log-level DEBUG C:\Users\username\
> Videos\My-video.mp4
> DEBUG:root:Logger level set to DEBUG
> DEBUG:root:Working with 4 threads
> DEBUG:root:Work directory set to temp
> DEBUG:root:Output directory set to output
> DEBUG:root:regex_replace list is: "re.compile(' +')" to " "; "re.compile('’')" to "'"; "re.compile('‘')" to "'"; "re.compile(" +'")" to "'"; "re.compile('([^ ])!')" to "\1 !"; "re.compile('([^ ])\\?')" to "\1 ?"; "re.compile('<i>-</i>')" to "-"; "re.compile('\\W<i>([A-Za-z0-9]+\\.\\.\\.)</i>')" to "\1"; "re.compile("I'")" to "l'"; "re.compile('^Gomme')" to "Comme"; "re.compile('\\nGomme')" to "\nComme"; "re.compile('_')" to ""; "re.compile('^II ')" to "Il "; "re.compile('\\|')" to "l"; "re.compile('^A ')" to "À "; "re.compile('\\nA ')" to "\nÀ "
> DEBUG:root:heurist_char_replace list is: "-" to ""; "I" to "l"; "e" to "é"; "e" to "ê"; "e" to "è"; "a" to "à"; "G" to "C"
> DEBUG:root:Creating directory at path temp
> INFO:root:Processing My-video.mp4, file 1 of 1
> INFO:root:Starting to filter file C:\Users\a\VideosMy-video.mp4
> DEBUG:root:Command used: vspipe -y --arg FichierSource="C:\Users\a\Videos\My-video.mp4" My-vpy.vpy - | ffmpeg -i - -c:v mpeg4 -qscale:v 3 -y "output/My-video.mp4"
> ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
>   built with gcc 7.1.0 (GCC)
>   configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
>   libavutil      55. 58.100 / 55. 58.100
>   libavcodec     57. 89.100 / 57. 89.100
>   libavformat    57. 71.100 / 57. 71.100
>   libavdevice    57.  6.100 / 57.  6.100
>   libavfilter     6. 82.100 /  6. 82.100
>   libswscale      4.  6.100 /  4.  6.100
>   libswresample   2.  7.100 /  2.  7.100
>   libpostproc    54.  5.100 / 54.  5.100
> Input #0, yuv4mpegpipe, from 'pipe:':
>   Duration: N/A, start: 0.000000, bitrate: N/A
>     Stream #0:0: Video: rawvideo (Y800 / 0x30303859), gray(progressive), 1494x300, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
> output/My-video.mp4: No such file or directory
> Traceback (most recent call last):
>   File "C:\Python36-32\lib\shutil.py", line 544, in move
>     os.rename(src, real_dst)
> FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'SceneChanges.log' -> 'output/My-video.log'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File ".\pythoCR.py", line 542, in <module>
>     subsdata = job(file, args.outputdir) if args.mode == "filter" else job(file)
>   File ".\pythoCR.py", line 316, in filter_only
>     shutil.move("SceneChanges.log", outputdir + "/" + os.path.splitext(os.path.basename(path))[0] + ".log")
>   File "C:\Python36-32\lib\shutil.py", line 558, in move
>     copy_function(src, real_dst)
>   File "C:\Python36-32\lib\shutil.py", line 257, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "C:\Python36-32\lib\shutil.py", line 121, in copyfile
>     with open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'output/My-video.log'
> Error: fwrite() call failed when writing frame: 1, plane: 0, line: 9, errno: 22
> Output 5 frames in 1.01 seconds (4.94 fps)`

**Comment by pocketsnizort** [comment]
Hi, thanks for the feedback, could you please give me the content of your config file (.\config\userconfig_2.ini) ?

**Comment by NekoKawaii** [comment]
For sure, here it is : 

```
regex-replace = config\regex_replace.json

sub-format = ass

heuristic-char-replace = config\char_replace.json

auto-same-sub-threshold = 95.
```

**Comment by pocketsnizort** [comment]
do you have an "output" folder created ?

**Comment by pocketsnizort** [comment]
fixed by commit 8feaca37419eae5ef7f997160beb711c1fed5b74

**Comment by NekoKawaii** [comment]
No, I don't, I'll try to fix it and I'll send a pull request if it works.

**Comment by NekoKawaii** [comment]
Pulled, it fixes the problem, so I can close this issue.
