### ISSUE TITLE
userconfig.ini ass-styles

### ISSUE THREAD

**Issue by ArturiaPendragon** [pocketsnizort/pythOCR#7]
Hello, please add support to multiples lines to variables ass-styles 👍

**Comment by pocketsnizort** [comment]
Hello, thanks for the feedback.
It is a great idea but currently, pythOCR only supports one style, there is no differentiation between styles other than top or bottom position. Position that is handled with the tag `{\an8}` in ass.

So it is very unlikely than other styles will be needed/used in the near future.
